import type { Metadata } from "next";
import { NextAuthProvider } from "@/app/api/auth/providers";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import Login from "./login";

export const metadata: Metadata = {
  title: "JL-Site - Admin",
  description: "Generated by create next app",
};

const AuthLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const session = await getServerSession(authOptions);
  console.log(session);
  return (
    <NextAuthProvider>
      {!!session && children}
      {!session && <Login />}
    </NextAuthProvider>
  );
};

export default AuthLayout;
